pr-range_diff: make more friendly
Give an actual usage example, check for missing GitHub token, give a
hint on missing remote.

Signed-off-by: Tomi Fontanilles <tomi.fontanilles@nordicsemi.no>

diff --git a/pr-range-diff b/pr-range-diff
--- a/pr-range-diff
+++ b/pr-range-diff
@@ -1,7 +1,14 @@
 #!/bin/bash
 
 if [ $# -ne 2 ]; then
-	echo "usage: $0 <PR URL> <from-commit URL>"
+	echo "usage: `basename $0` <PR URL> <from-commit URL>"
+	echo -e "\nexample: `basename $0` https://github.com/zephyrproject-rtos/zephyr/pull/116318 https://github.com/zephyrproject-rtos/zephyr/commit/301c36b47f1402a3bf5ee550c9e51d0cabbe920b"
+	exit 1
+fi
+
+token_path=`dirname "$0"`/github_token
+if ! [ -f "$token_path" ]; then
+	echo "missing token ($token_path not found)"
 	exit 1
 fi
 
@@ -9,15 +16,15 @@ pr_num=$(cut -d / -f 7 <<< $1 | cut -d# -f1)
 from_rev=$(cut -d / -f 7 <<< $2)
 remote=$(git remote -v | grep -m 1 -F "$(cut -d / -f 1-5 <<< $1)" | cut -d $'\t' -f 1)
 if [ "$remote" = "" ]; then
-	echo "missing remote"
+	echo "missing remote - Did you run this from the repository you are range-diffing?"
 	exit 1
 fi
 
 repo=$(cut -d / -f 4-5 <<< $1)
-token=$(cat `dirname "$0"`/github_token)
+token=$(cat "$token_path")
 base=$(curl -s -H "Authorization: token $token" "https://api.github.com/repos/$repo/pulls/$pr_num" | jq -r '.base.ref')
 if [ "$base" == 'null' ]; then
-	echo "Failed to retrieve .base.ref"
+	echo "failed to retrieve .base.ref"
 	exit 1
 fi
 
